<?php

/**
 * Base static class for performing query and update operations on the 'sf_guard_user' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Aug 13 13:01:59 2011
 *
 * @package    plugins.sfGuardPlugin.lib.model.om
 */
abstract class BasesfGuardUserPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'sf_guard_user';

	/** the related Propel class for this table */
	const OM_CLASS = 'sfGuardUser';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'plugins.sfGuardPlugin.lib.model.sfGuardUser';

	/** the related TableMap class for this table */
	const TM_CLASS = 'sfGuardUserTableMap';
	
	/** The total number of columns. */
	const NUM_COLUMNS = 36;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'sf_guard_user.ID';

	/** the column name for the FIRST_NAME field */
	const FIRST_NAME = 'sf_guard_user.FIRST_NAME';

	/** the column name for the LAST_NAME field */
	const LAST_NAME = 'sf_guard_user.LAST_NAME';

	/** the column name for the EMAIL_ADDRESS field */
	const EMAIL_ADDRESS = 'sf_guard_user.EMAIL_ADDRESS';

	/** the column name for the USERNAME field */
	const USERNAME = 'sf_guard_user.USERNAME';

	/** the column name for the ALGORITHM field */
	const ALGORITHM = 'sf_guard_user.ALGORITHM';

	/** the column name for the SALT field */
	const SALT = 'sf_guard_user.SALT';

	/** the column name for the PASSWORD field */
	const PASSWORD = 'sf_guard_user.PASSWORD';

	/** the column name for the SEX field */
	const SEX = 'sf_guard_user.SEX';

	/** the column name for the BIRTHDAY field */
	const BIRTHDAY = 'sf_guard_user.BIRTHDAY';

	/** the column name for the ABOUTME field */
	const ABOUTME = 'sf_guard_user.ABOUTME';

	/** the column name for the PROFESSION field */
	const PROFESSION = 'sf_guard_user.PROFESSION';

	/** the column name for the MUSIC field */
	const MUSIC = 'sf_guard_user.MUSIC';

	/** the column name for the BOOKS field */
	const BOOKS = 'sf_guard_user.BOOKS';

	/** the column name for the FILMS field */
	const FILMS = 'sf_guard_user.FILMS';

	/** the column name for the TELEVISION field */
	const TELEVISION = 'sf_guard_user.TELEVISION';

	/** the column name for the GAMES field */
	const GAMES = 'sf_guard_user.GAMES';

	/** the column name for the MARITAL_STATUS field */
	const MARITAL_STATUS = 'sf_guard_user.MARITAL_STATUS';

	/** the column name for the MEETING_SEX field */
	const MEETING_SEX = 'sf_guard_user.MEETING_SEX';

	/** the column name for the HOMETOWN field */
	const HOMETOWN = 'sf_guard_user.HOMETOWN';

	/** the column name for the BORNTOWN field */
	const BORNTOWN = 'sf_guard_user.BORNTOWN';

	/** the column name for the SMOKER field */
	const SMOKER = 'sf_guard_user.SMOKER';

	/** the column name for the DRINKER field */
	const DRINKER = 'sf_guard_user.DRINKER';

	/** the column name for the EDUCATION field */
	const EDUCATION = 'sf_guard_user.EDUCATION';

	/** the column name for the LANGUAGE field */
	const LANGUAGE = 'sf_guard_user.LANGUAGE';

	/** the column name for the RELIGION field */
	const RELIGION = 'sf_guard_user.RELIGION';

	/** the column name for the POLITIC field */
	const POLITIC = 'sf_guard_user.POLITIC';

	/** the column name for the COUNTRY field */
	const COUNTRY = 'sf_guard_user.COUNTRY';

	/** the column name for the CITY field */
	const CITY = 'sf_guard_user.CITY';

	/** the column name for the CP field */
	const CP = 'sf_guard_user.CP';

	/** the column name for the DESCRIPTION field */
	const DESCRIPTION = 'sf_guard_user.DESCRIPTION';

	/** the column name for the CONTACT field */
	const CONTACT = 'sf_guard_user.CONTACT';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'sf_guard_user.CREATED_AT';

	/** the column name for the LAST_LOGIN field */
	const LAST_LOGIN = 'sf_guard_user.LAST_LOGIN';

	/** the column name for the IS_ACTIVE field */
	const IS_ACTIVE = 'sf_guard_user.IS_ACTIVE';

	/** the column name for the IS_SUPER_ADMIN field */
	const IS_SUPER_ADMIN = 'sf_guard_user.IS_SUPER_ADMIN';

	/**
	 * An identiy map to hold any loaded instances of sfGuardUser objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array sfGuardUser[]
	 */
	public static $instances = array();


	// symfony behavior
	
	/**
	 * Indicates whether the current model includes I18N.
	 */
	const IS_I18N = false;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'FirstName', 'LastName', 'EmailAddress', 'Username', 'Algorithm', 'Salt', 'Password', 'Sex', 'Birthday', 'Aboutme', 'Profession', 'Music', 'Books', 'Films', 'Television', 'Games', 'MaritalStatus', 'MeetingSex', 'Hometown', 'Borntown', 'Smoker', 'Drinker', 'Education', 'Language', 'Religion', 'Politic', 'Country', 'City', 'Cp', 'Description', 'Contact', 'CreatedAt', 'LastLogin', 'IsActive', 'IsSuperAdmin', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'firstName', 'lastName', 'emailAddress', 'username', 'algorithm', 'salt', 'password', 'sex', 'birthday', 'aboutme', 'profession', 'music', 'books', 'films', 'television', 'games', 'maritalStatus', 'meetingSex', 'hometown', 'borntown', 'smoker', 'drinker', 'education', 'language', 'religion', 'politic', 'country', 'city', 'cp', 'description', 'contact', 'createdAt', 'lastLogin', 'isActive', 'isSuperAdmin', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::FIRST_NAME, self::LAST_NAME, self::EMAIL_ADDRESS, self::USERNAME, self::ALGORITHM, self::SALT, self::PASSWORD, self::SEX, self::BIRTHDAY, self::ABOUTME, self::PROFESSION, self::MUSIC, self::BOOKS, self::FILMS, self::TELEVISION, self::GAMES, self::MARITAL_STATUS, self::MEETING_SEX, self::HOMETOWN, self::BORNTOWN, self::SMOKER, self::DRINKER, self::EDUCATION, self::LANGUAGE, self::RELIGION, self::POLITIC, self::COUNTRY, self::CITY, self::CP, self::DESCRIPTION, self::CONTACT, self::CREATED_AT, self::LAST_LOGIN, self::IS_ACTIVE, self::IS_SUPER_ADMIN, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'first_name', 'last_name', 'email_address', 'username', 'algorithm', 'salt', 'password', 'sex', 'birthday', 'aboutme', 'profession', 'music', 'books', 'films', 'television', 'games', 'marital_status', 'meeting_sex', 'hometown', 'borntown', 'smoker', 'drinker', 'education', 'language', 'religion', 'politic', 'country', 'city', 'cp', 'description', 'contact', 'created_at', 'last_login', 'is_active', 'is_super_admin', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'FirstName' => 1, 'LastName' => 2, 'EmailAddress' => 3, 'Username' => 4, 'Algorithm' => 5, 'Salt' => 6, 'Password' => 7, 'Sex' => 8, 'Birthday' => 9, 'Aboutme' => 10, 'Profession' => 11, 'Music' => 12, 'Books' => 13, 'Films' => 14, 'Television' => 15, 'Games' => 16, 'MaritalStatus' => 17, 'MeetingSex' => 18, 'Hometown' => 19, 'Borntown' => 20, 'Smoker' => 21, 'Drinker' => 22, 'Education' => 23, 'Language' => 24, 'Religion' => 25, 'Politic' => 26, 'Country' => 27, 'City' => 28, 'Cp' => 29, 'Description' => 30, 'Contact' => 31, 'CreatedAt' => 32, 'LastLogin' => 33, 'IsActive' => 34, 'IsSuperAdmin' => 35, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'firstName' => 1, 'lastName' => 2, 'emailAddress' => 3, 'username' => 4, 'algorithm' => 5, 'salt' => 6, 'password' => 7, 'sex' => 8, 'birthday' => 9, 'aboutme' => 10, 'profession' => 11, 'music' => 12, 'books' => 13, 'films' => 14, 'television' => 15, 'games' => 16, 'maritalStatus' => 17, 'meetingSex' => 18, 'hometown' => 19, 'borntown' => 20, 'smoker' => 21, 'drinker' => 22, 'education' => 23, 'language' => 24, 'religion' => 25, 'politic' => 26, 'country' => 27, 'city' => 28, 'cp' => 29, 'description' => 30, 'contact' => 31, 'createdAt' => 32, 'lastLogin' => 33, 'isActive' => 34, 'isSuperAdmin' => 35, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::FIRST_NAME => 1, self::LAST_NAME => 2, self::EMAIL_ADDRESS => 3, self::USERNAME => 4, self::ALGORITHM => 5, self::SALT => 6, self::PASSWORD => 7, self::SEX => 8, self::BIRTHDAY => 9, self::ABOUTME => 10, self::PROFESSION => 11, self::MUSIC => 12, self::BOOKS => 13, self::FILMS => 14, self::TELEVISION => 15, self::GAMES => 16, self::MARITAL_STATUS => 17, self::MEETING_SEX => 18, self::HOMETOWN => 19, self::BORNTOWN => 20, self::SMOKER => 21, self::DRINKER => 22, self::EDUCATION => 23, self::LANGUAGE => 24, self::RELIGION => 25, self::POLITIC => 26, self::COUNTRY => 27, self::CITY => 28, self::CP => 29, self::DESCRIPTION => 30, self::CONTACT => 31, self::CREATED_AT => 32, self::LAST_LOGIN => 33, self::IS_ACTIVE => 34, self::IS_SUPER_ADMIN => 35, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'first_name' => 1, 'last_name' => 2, 'email_address' => 3, 'username' => 4, 'algorithm' => 5, 'salt' => 6, 'password' => 7, 'sex' => 8, 'birthday' => 9, 'aboutme' => 10, 'profession' => 11, 'music' => 12, 'books' => 13, 'films' => 14, 'television' => 15, 'games' => 16, 'marital_status' => 17, 'meeting_sex' => 18, 'hometown' => 19, 'borntown' => 20, 'smoker' => 21, 'drinker' => 22, 'education' => 23, 'language' => 24, 'religion' => 25, 'politic' => 26, 'country' => 27, 'city' => 28, 'cp' => 29, 'description' => 30, 'contact' => 31, 'created_at' => 32, 'last_login' => 33, 'is_active' => 34, 'is_super_admin' => 35, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, )
	);

	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. sfGuardUserPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(sfGuardUserPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{
		$criteria->addSelectColumn(sfGuardUserPeer::ID);
		$criteria->addSelectColumn(sfGuardUserPeer::FIRST_NAME);
		$criteria->addSelectColumn(sfGuardUserPeer::LAST_NAME);
		$criteria->addSelectColumn(sfGuardUserPeer::EMAIL_ADDRESS);
		$criteria->addSelectColumn(sfGuardUserPeer::USERNAME);
		$criteria->addSelectColumn(sfGuardUserPeer::ALGORITHM);
		$criteria->addSelectColumn(sfGuardUserPeer::SALT);
		$criteria->addSelectColumn(sfGuardUserPeer::PASSWORD);
		$criteria->addSelectColumn(sfGuardUserPeer::SEX);
		$criteria->addSelectColumn(sfGuardUserPeer::BIRTHDAY);
		$criteria->addSelectColumn(sfGuardUserPeer::ABOUTME);
		$criteria->addSelectColumn(sfGuardUserPeer::PROFESSION);
		$criteria->addSelectColumn(sfGuardUserPeer::MUSIC);
		$criteria->addSelectColumn(sfGuardUserPeer::BOOKS);
		$criteria->addSelectColumn(sfGuardUserPeer::FILMS);
		$criteria->addSelectColumn(sfGuardUserPeer::TELEVISION);
		$criteria->addSelectColumn(sfGuardUserPeer::GAMES);
		$criteria->addSelectColumn(sfGuardUserPeer::MARITAL_STATUS);
		$criteria->addSelectColumn(sfGuardUserPeer::MEETING_SEX);
		$criteria->addSelectColumn(sfGuardUserPeer::HOMETOWN);
		$criteria->addSelectColumn(sfGuardUserPeer::BORNTOWN);
		$criteria->addSelectColumn(sfGuardUserPeer::SMOKER);
		$criteria->addSelectColumn(sfGuardUserPeer::DRINKER);
		$criteria->addSelectColumn(sfGuardUserPeer::EDUCATION);
		$criteria->addSelectColumn(sfGuardUserPeer::LANGUAGE);
		$criteria->addSelectColumn(sfGuardUserPeer::RELIGION);
		$criteria->addSelectColumn(sfGuardUserPeer::POLITIC);
		$criteria->addSelectColumn(sfGuardUserPeer::COUNTRY);
		$criteria->addSelectColumn(sfGuardUserPeer::CITY);
		$criteria->addSelectColumn(sfGuardUserPeer::CP);
		$criteria->addSelectColumn(sfGuardUserPeer::DESCRIPTION);
		$criteria->addSelectColumn(sfGuardUserPeer::CONTACT);
		$criteria->addSelectColumn(sfGuardUserPeer::CREATED_AT);
		$criteria->addSelectColumn(sfGuardUserPeer::LAST_LOGIN);
		$criteria->addSelectColumn(sfGuardUserPeer::IS_ACTIVE);
		$criteria->addSelectColumn(sfGuardUserPeer::IS_SUPER_ADMIN);
	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(sfGuardUserPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			sfGuardUserPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(sfGuardUserPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasesfGuardUserPeer', $criteria, $con);
		}

		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     sfGuardUser
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = sfGuardUserPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return sfGuardUserPeer::populateObjects(sfGuardUserPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(sfGuardUserPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			sfGuardUserPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);
		// symfony_behaviors behavior
		foreach (sfMixer::getCallables(self::getMixerPreSelectHook(__FUNCTION__)) as $sf_hook)
		{
		  call_user_func($sf_hook, 'BasesfGuardUserPeer', $criteria, $con);
		}


		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      sfGuardUser $value A sfGuardUser object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(sfGuardUser $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A sfGuardUser object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof sfGuardUser) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or sfGuardUser object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     sfGuardUser Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Method to invalidate the instance pool of all tables related to sf_guard_user
	 * by a foreign key with ON DELETE CASCADE
	 */
	public static function clearRelatedInstancePool()
	{
		// invalidate objects in inboxPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		inboxPeer::clearInstancePool();

		// invalidate objects in inboxPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		inboxPeer::clearInstancePool();

		// invalidate objects in sfGuardUserPermissionPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		sfGuardUserPermissionPeer::clearInstancePool();

		// invalidate objects in sfGuardUserGroupPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		sfGuardUserGroupPeer::clearInstancePool();

		// invalidate objects in sfGuardRememberKeyPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		sfGuardRememberKeyPeer::clearInstancePool();

		// invalidate objects in SfguardforgotpasswordPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		SfguardforgotpasswordPeer::clearInstancePool();

		// invalidate objects in LocationPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		LocationPeer::clearInstancePool();

		// invalidate objects in FavlikePeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		FavlikePeer::clearInstancePool();

		// invalidate objects in FavlikePeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		FavlikePeer::clearInstancePool();

		// invalidate objects in CommentPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		CommentPeer::clearInstancePool();

		// invalidate objects in CommentPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		CommentPeer::clearInstancePool();

		// invalidate objects in PubsPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		PubsPeer::clearInstancePool();

		// invalidate objects in PubsPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		PubsPeer::clearInstancePool();

		// invalidate objects in AudioPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		AudioPeer::clearInstancePool();

		// invalidate objects in AudioPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		AudioPeer::clearInstancePool();

		// invalidate objects in PlaylistPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		PlaylistPeer::clearInstancePool();

		// invalidate objects in TextPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		TextPeer::clearInstancePool();

		// invalidate objects in LinkPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		LinkPeer::clearInstancePool();

		// invalidate objects in FollowPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		FollowPeer::clearInstancePool();

		// invalidate objects in FollowPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		FollowPeer::clearInstancePool();

		// invalidate objects in NotificationPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		NotificationPeer::clearInstancePool();

		// invalidate objects in NotificationPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		NotificationPeer::clearInstancePool();

		// invalidate objects in SettingHasUserPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		SettingHasUserPeer::clearInstancePool();

		// invalidate objects in EventPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		EventPeer::clearInstancePool();

		// invalidate objects in AlbumPhotoPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		AlbumPhotoPeer::clearInstancePool();

		// invalidate objects in ProfilePhotoPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
		ProfilePhotoPeer::clearInstancePool();

	}

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol] === null) {
			return null;
		}
		return (string) $row[$startcol];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = sfGuardUserPeer::getOMClass(false);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = sfGuardUserPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = sfGuardUserPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				sfGuardUserPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * Add a TableMap instance to the database for this peer class.
	 */
	public static function buildTableMap()
	{
	  $dbMap = Propel::getDatabaseMap(BasesfGuardUserPeer::DATABASE_NAME);
	  if (!$dbMap->hasTable(BasesfGuardUserPeer::TABLE_NAME))
	  {
	    $dbMap->addTableObject(new sfGuardUserTableMap());
	  }
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * If $withPrefix is true, the returned path
	 * uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @param      boolean  Whether or not to return the path wit hthe class name 
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass($withPrefix = true)
	{
		return $withPrefix ? sfGuardUserPeer::CLASS_DEFAULT : sfGuardUserPeer::OM_CLASS;
	}

	/**
	 * Method perform an INSERT on the database, given a sfGuardUser or Criteria object.
	 *
	 * @param      mixed $values Criteria or sfGuardUser object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasesfGuardUserPeer:doInsert:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BasesfGuardUserPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(sfGuardUserPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from sfGuardUser object
		}

		if ($criteria->containsKey(sfGuardUserPeer::ID) && $criteria->keyContainsValue(sfGuardUserPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.sfGuardUserPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasesfGuardUserPeer:doInsert:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BasesfGuardUserPeer', $values, $con, $pk);
    }

		return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a sfGuardUser or Criteria object.
	 *
	 * @param      mixed $values Criteria or sfGuardUser object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{
    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasesfGuardUserPeer:doUpdate:pre') as $sf_hook)
    {
      if (false !== $sf_hook_retval = call_user_func($sf_hook, 'BasesfGuardUserPeer', $values, $con))
      {
        return $sf_hook_retval;
      }
    }

		if ($con === null) {
			$con = Propel::getConnection(sfGuardUserPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(sfGuardUserPeer::ID);
			$selectCriteria->add(sfGuardUserPeer::ID, $criteria->remove(sfGuardUserPeer::ID), $comparison);

		} else { // $values is sfGuardUser object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);

    // symfony_behaviors behavior
    foreach (sfMixer::getCallables('BasesfGuardUserPeer:doUpdate:post') as $sf_hook)
    {
      call_user_func($sf_hook, 'BasesfGuardUserPeer', $values, $con, $ret);
    }

    return $ret;
	}

	/**
	 * Method to DELETE all rows from the sf_guard_user table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(sfGuardUserPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += sfGuardUserPeer::doOnDeleteCascade(new Criteria(sfGuardUserPeer::DATABASE_NAME), $con);
			$affectedRows += BasePeer::doDeleteAll(sfGuardUserPeer::TABLE_NAME, $con);
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			sfGuardUserPeer::clearInstancePool();
			sfGuardUserPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a sfGuardUser or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or sfGuardUser object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(sfGuardUserPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof sfGuardUser) { // it's a model object
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else { // it's a primary key, or an array of pks
			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(sfGuardUserPeer::ID, (array) $values, Criteria::IN);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += sfGuardUserPeer::doOnDeleteCascade($criteria, $con);
			
			// Because this db requires some delete cascade/set null emulation, we have to
			// clear the cached instance *after* the emulation has happened (since
			// instances get re-added by the select statement contained therein).
			if ($values instanceof Criteria) {
				sfGuardUserPeer::clearInstancePool();
			} elseif ($values instanceof sfGuardUser) { // it's a model object
				sfGuardUserPeer::removeInstanceFromPool($values);
			} else { // it's a primary key, or an array of pks
				foreach ((array) $values as $singleval) {
					sfGuardUserPeer::removeInstanceFromPool($singleval);
				}
			}
			
			$affectedRows += BasePeer::doDelete($criteria, $con);
			sfGuardUserPeer::clearRelatedInstancePool();
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * This is a method for emulating ON DELETE CASCADE for DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	protected static function doOnDeleteCascade(Criteria $criteria, PropelPDO $con)
	{
		// initialize var to track total num of affected rows
		$affectedRows = 0;

		// first find the objects that are implicated by the $criteria
		$objects = sfGuardUserPeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {


			// delete related inbox objects
			$criteria = new Criteria(inboxPeer::DATABASE_NAME);
			
			$criteria->add(inboxPeer::USER_ID, $obj->getId());
			$affectedRows += inboxPeer::doDelete($criteria, $con);

			// delete related inbox objects
			$criteria = new Criteria(inboxPeer::DATABASE_NAME);
			
			$criteria->add(inboxPeer::DEST_USER_ID, $obj->getId());
			$affectedRows += inboxPeer::doDelete($criteria, $con);

			// delete related sfGuardUserPermission objects
			$criteria = new Criteria(sfGuardUserPermissionPeer::DATABASE_NAME);
			
			$criteria->add(sfGuardUserPermissionPeer::USER_ID, $obj->getId());
			$affectedRows += sfGuardUserPermissionPeer::doDelete($criteria, $con);

			// delete related sfGuardUserGroup objects
			$criteria = new Criteria(sfGuardUserGroupPeer::DATABASE_NAME);
			
			$criteria->add(sfGuardUserGroupPeer::USER_ID, $obj->getId());
			$affectedRows += sfGuardUserGroupPeer::doDelete($criteria, $con);

			// delete related sfGuardRememberKey objects
			$criteria = new Criteria(sfGuardRememberKeyPeer::DATABASE_NAME);
			
			$criteria->add(sfGuardRememberKeyPeer::USER_ID, $obj->getId());
			$affectedRows += sfGuardRememberKeyPeer::doDelete($criteria, $con);

			// delete related Sfguardforgotpassword objects
			$criteria = new Criteria(SfguardforgotpasswordPeer::DATABASE_NAME);
			
			$criteria->add(SfguardforgotpasswordPeer::USER_ID, $obj->getId());
			$affectedRows += SfguardforgotpasswordPeer::doDelete($criteria, $con);

			// delete related Location objects
			$criteria = new Criteria(LocationPeer::DATABASE_NAME);
			
			$criteria->add(LocationPeer::USER_ID, $obj->getId());
			$affectedRows += LocationPeer::doDelete($criteria, $con);

			// delete related Favlike objects
			$criteria = new Criteria(FavlikePeer::DATABASE_NAME);
			
			$criteria->add(FavlikePeer::USER_ID, $obj->getId());
			$affectedRows += FavlikePeer::doDelete($criteria, $con);

			// delete related Favlike objects
			$criteria = new Criteria(FavlikePeer::DATABASE_NAME);
			
			$criteria->add(FavlikePeer::DEST_USER_ID, $obj->getId());
			$affectedRows += FavlikePeer::doDelete($criteria, $con);

			// delete related Comment objects
			$criteria = new Criteria(CommentPeer::DATABASE_NAME);
			
			$criteria->add(CommentPeer::USER_ID, $obj->getId());
			$affectedRows += CommentPeer::doDelete($criteria, $con);

			// delete related Comment objects
			$criteria = new Criteria(CommentPeer::DATABASE_NAME);
			
			$criteria->add(CommentPeer::DEST_USER_ID, $obj->getId());
			$affectedRows += CommentPeer::doDelete($criteria, $con);

			// delete related Pubs objects
			$criteria = new Criteria(PubsPeer::DATABASE_NAME);
			
			$criteria->add(PubsPeer::USER_ID, $obj->getId());
			$affectedRows += PubsPeer::doDelete($criteria, $con);

			// delete related Pubs objects
			$criteria = new Criteria(PubsPeer::DATABASE_NAME);
			
			$criteria->add(PubsPeer::DEST_USER_ID, $obj->getId());
			$affectedRows += PubsPeer::doDelete($criteria, $con);

			// delete related Audio objects
			$criteria = new Criteria(AudioPeer::DATABASE_NAME);
			
			$criteria->add(AudioPeer::USER_ID, $obj->getId());
			$affectedRows += AudioPeer::doDelete($criteria, $con);

			// delete related Audio objects
			$criteria = new Criteria(AudioPeer::DATABASE_NAME);
			
			$criteria->add(AudioPeer::DEST_USER_ID, $obj->getId());
			$affectedRows += AudioPeer::doDelete($criteria, $con);

			// delete related Playlist objects
			$criteria = new Criteria(PlaylistPeer::DATABASE_NAME);
			
			$criteria->add(PlaylistPeer::USER_ID, $obj->getId());
			$affectedRows += PlaylistPeer::doDelete($criteria, $con);

			// delete related Text objects
			$criteria = new Criteria(TextPeer::DATABASE_NAME);
			
			$criteria->add(TextPeer::USER_ID, $obj->getId());
			$affectedRows += TextPeer::doDelete($criteria, $con);

			// delete related Link objects
			$criteria = new Criteria(LinkPeer::DATABASE_NAME);
			
			$criteria->add(LinkPeer::USER_ID, $obj->getId());
			$affectedRows += LinkPeer::doDelete($criteria, $con);

			// delete related Follow objects
			$criteria = new Criteria(FollowPeer::DATABASE_NAME);
			
			$criteria->add(FollowPeer::USER_ID, $obj->getId());
			$affectedRows += FollowPeer::doDelete($criteria, $con);

			// delete related Follow objects
			$criteria = new Criteria(FollowPeer::DATABASE_NAME);
			
			$criteria->add(FollowPeer::FOLLOW_ID, $obj->getId());
			$affectedRows += FollowPeer::doDelete($criteria, $con);

			// delete related Notification objects
			$criteria = new Criteria(NotificationPeer::DATABASE_NAME);
			
			$criteria->add(NotificationPeer::USER_ID, $obj->getId());
			$affectedRows += NotificationPeer::doDelete($criteria, $con);

			// delete related Notification objects
			$criteria = new Criteria(NotificationPeer::DATABASE_NAME);
			
			$criteria->add(NotificationPeer::DEST_USER_ID, $obj->getId());
			$affectedRows += NotificationPeer::doDelete($criteria, $con);

			// delete related SettingHasUser objects
			$criteria = new Criteria(SettingHasUserPeer::DATABASE_NAME);
			
			$criteria->add(SettingHasUserPeer::USER_ID, $obj->getId());
			$affectedRows += SettingHasUserPeer::doDelete($criteria, $con);

			// delete related Event objects
			$criteria = new Criteria(EventPeer::DATABASE_NAME);
			
			$criteria->add(EventPeer::USER_ID, $obj->getId());
			$affectedRows += EventPeer::doDelete($criteria, $con);

			// delete related AlbumPhoto objects
			$criteria = new Criteria(AlbumPhotoPeer::DATABASE_NAME);
			
			$criteria->add(AlbumPhotoPeer::USER_ID, $obj->getId());
			$affectedRows += AlbumPhotoPeer::doDelete($criteria, $con);

			// delete related ProfilePhoto objects
			$criteria = new Criteria(ProfilePhotoPeer::DATABASE_NAME);
			
			$criteria->add(ProfilePhotoPeer::USER_ID, $obj->getId());
			$affectedRows += ProfilePhotoPeer::doDelete($criteria, $con);
		}
		return $affectedRows;
	}

	/**
	 * Validates all modified columns of given sfGuardUser object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      sfGuardUser $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(sfGuardUser $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(sfGuardUserPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(sfGuardUserPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		return BasePeer::doValidate(sfGuardUserPeer::DATABASE_NAME, sfGuardUserPeer::TABLE_NAME, $columns);
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     sfGuardUser
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = sfGuardUserPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(sfGuardUserPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(sfGuardUserPeer::DATABASE_NAME);
		$criteria->add(sfGuardUserPeer::ID, $pk);

		$v = sfGuardUserPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(sfGuardUserPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(sfGuardUserPeer::DATABASE_NAME);
			$criteria->add(sfGuardUserPeer::ID, $pks, Criteria::IN);
			$objs = sfGuardUserPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

	// symfony behavior
	
	/**
	 * Returns an array of arrays that contain columns in each unique index.
	 *
	 * @return array
	 */
	static public function getUniqueColumnNames()
	{
	  return array(array('email_address'), array('username'));
	}

	// symfony_behaviors behavior
	
	/**
	 * Returns the name of the hook to call from inside the supplied method.
	 *
	 * @param string $method The calling method
	 *
	 * @return string A hook name for {@link sfMixer}
	 *
	 * @throws LogicException If the method name is not recognized
	 */
	static private function getMixerPreSelectHook($method)
	{
	  if (preg_match('/^do(Select|Count)(Join(All(Except)?)?|Stmt)?/', $method, $match))
	  {
	    return sprintf('BasesfGuardUserPeer:%s:%1$s', 'Count' == $match[1] ? 'doCount' : $match[0]);
	  }
	
	  throw new LogicException(sprintf('Unrecognized function "%s"', $method));
	}

} // BasesfGuardUserPeer

// This is the static code needed to register the TableMap for this table with the main Propel class.
//
BasesfGuardUserPeer::buildTableMap();

