<?php


/**
 * This class defines the structure of the 'Audio_has_playlist' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Aug 13 13:02:00 2011
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    plugins.PubsPlugin.lib.model.map
 */
class AudioHasPlaylistTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'plugins.PubsPlugin.lib.model.map.AudioHasPlaylistTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('Audio_has_playlist');
		$this->setPhpName('AudioHasPlaylist');
		$this->setClassname('AudioHasPlaylist');
		$this->setPackage('plugins.PubsPlugin.lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addForeignKey('AUDIO_ID', 'AudioId', 'INTEGER', 'Audio', 'ID', false, null, null);
		$this->addForeignKey('PL_ID', 'PlId', 'INTEGER', 'Playlist', 'ID', false, null, null);
		$this->addColumn('ORDEN', 'Orden', 'INTEGER', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Audio', 'Audio', RelationMap::MANY_TO_ONE, array('audio_id' => 'id', ), 'CASCADE', null);
    $this->addRelation('Playlist', 'Playlist', RelationMap::MANY_TO_ONE, array('pl_id' => 'id', ), 'CASCADE', null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // AudioHasPlaylistTableMap
