<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/17 16:30:33
sfConfig::add(array(
  'app_gmap_key' => 'ABQIAAAAddW2_j-icZZyAl1A2ya7rhTmBmdW71nIF5MtmjpH_tuHEHNTXxTc_YkG716w5faDwp6nEt0ZjvZO-w',
  'app_audio_commentable' => true,
  'app_audio_favlikeable' => true,
  'app_sf_guard_plugin_success_signin_url' => 'http://sandbox_1_3/frontend_dev.php',
  'app_base_url' => 'http://sandbox_1_3/',
  'app_site_name' => 'Social sandbox',
));
