<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/17 16:33:30
sfConfig::add(array(
  'mod_audio_enabled' => true,
  'mod_audio_view_class' => 'sfPHP',
  'mod_audio_is_internal' => false,
));
