<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/17 16:30:39
sfConfig::add(array(
  'mod_text_enabled' => true,
  'mod_text_view_class' => 'sfPHP',
  'mod_text_is_internal' => false,
));
