<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/17 16:30:33
sfConfig::add(array(
  'mod_comment_enabled' => true,
  'mod_comment_view_class' => 'sfPHP',
  'mod_comment_is_internal' => false,
));
