<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/17 16:33:29
sfConfig::add(array(
  'mod_inbox_enabled' => true,
  'mod_inbox_view_class' => 'sfPHP',
  'mod_inbox_is_internal' => false,
));
