<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/17 16:33:33
sfConfig::add(array(
  'mod_notification_enabled' => true,
  'mod_notification_view_class' => 'sfPHP',
  'mod_notification_is_internal' => false,
));
