<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/17 16:33:29
sfConfig::add(array(
  'mod_language_enabled' => true,
  'mod_language_view_class' => 'sfPHP',
  'mod_language_is_internal' => false,
));
