<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/17 17:10:48
sfConfig::add(array(
  'mod_sfguardauth_enabled' => true,
  'mod_sfguardauth_view_class' => 'sfPHP',
  'mod_sfguardauth_is_internal' => false,
));
