<?php


/**
 * Skeleton subclass for representing a row from the 'Audio_has_playlist' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Aug 10 15:28:26 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.PubsPlugin.lib.model
 */
class AudioHasPlaylist extends BaseAudioHasPlaylist {

} // AudioHasPlaylist
