<?php

/**
 * Skeleton subclass for representing a row from the 'Event' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Aug 12 18:23:23 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.PubsPlugin.lib.model
 */
class Event extends BaseEvent {

    /**
     * Initializes internal state of Event object.
     * @see        parent::__construct()
     */
    public function __construct() {
        // Make sure that parent constructor is always invoked, since that
        // is where any default values for this object are set.
        parent::__construct();
    }

    public function getImagePath($tamanyo='thumb') {
        return '/users/' . $this->getUser()->getUsername() . '/eventImages/' . $tamanyo . '/' . $this->getimage();
    }

    public function isMine() {
        return $this->getUserId() == sfContext::getInstance()->getUser()->getGuardUser()->getId();
    }

    public function getDestUserId() {
        return $this->getUser()->getId();
    }

    public function getFavlikes() {
        $query = Doctrine::getTable('Favlike')->createQuery('p')
                ->where('p.record_id = ?', $this->_get('id'))
                ->andWhere('p.record_model = ?', 'event')
                ->leftJoin('p.User u')
                ->orderBy('p.created_at DESC');
        return $query->execute();
    }

    public function getComments() {
        $query = Doctrine::getTable('Comment')->createQuery('p')
                ->where('p.record_id = ?', $this->_get('id'))
                ->andWhere('p.record_model = ?', 'event')
                ->leftJoin('p.User u')
                ->orderBy('p.created_at ASC');
        return $query->execute();
    }

}

// Event
