<?php

/**
 * Skeleton subclass for performing query and update operations on the 'Favlike' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Aug 10 15:20:06 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.PubsPlugin.lib.model
 */
class FavlikePeer extends BaseFavlikePeer {
    
    public static function retrieveById($id) {
        $c = new Criteria();
        $c->add(self::ID, $id);
        return self::doSelectOne($c);
    }

    public static function getIsFavlike($user_id=null, $dest_user_id=null, $record_model=null, $record_id=null) {

        $i = new Criteria();
        $i->add(FavlikePeer::USER_ID, $user_id);
        $i->add(FavlikePeer::DEST_USER_ID, $dest_user_id);
        $i->add(FavlikePeer::RECORD_ID, $record_id);
        $i->add(FavlikePeer::RECORD_MODEL, $record_model);

        return $i = FavlikePeer::doSelectOne($i);

    }

    public static function activate($id=null) {
                $con = Propel::getConnection();

// select from...
        $c1 = new Criteria();
        $c1->add(self::ID, $id);

// update set
        $c2 = new Criteria();
        $c2->add(self::IS_ACTIVE, true);

        BasePeer::doUpdate($c1, $c2, $con);
//        
//        Doctrine_Query::create()
//                ->update('favlike f')
//                ->set('f.is_active', '?', true)
//                ->where('f.id = ?', $id)
//                ->execute();
    }

    public static function countFavlikes($id=null, $model=null) {
         $i = new Criteria();
            $i->add(FavlikePeer::RECORD_ID, $id);
            $i->add(FavlikePeer::RECORD_MODEL, $model);
        return count(FavlikePeer::doSelect($i));
    }

    public static function getFavlikes($user) {
        if (!is_numeric($user)) {
            $i = new Criteria();
            $i->add(sfGuardUserPeer::USERNAME, $user);
            $datos = sfGuardUserPeer::doSelectOne($i);
        } else {
            $datos = sfGuardUserPeer::retrieveByPk($user);
        }
        
        $i = new Criteria();
        $i->add(FavlikePeer::USER_ID, $datos->getId());
        return count(FavlikePeer::doSelect($i));
        
    }

}

// FavlikePeer
