<?php

/**
 * Skeleton subclass for representing a row from the 'Pubs' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Aug 10 15:12:00 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.PubsPlugin.lib.model
 */
class Pubs extends BasePubs {

    /**
     * Initializes internal state of Pubs object.
     * @see        parent::__construct()
     */
    public function __construct() {
        // Make sure that parent constructor is always invoked, since that
        // is where any default values for this object are set.
        parent::__construct();
    }
    
    public function getUser($id=null) {

        return sfGuardUserPeer::retrieveByPk($this->user_id);
    }
    
    public function getDestUser($id=null) {

        return sfGuardUserPeer::retrieveByPk($this->dest_user_id);
    }
    
    public function getObject() {
        $i = new Criteria();
        $model = $this->getRecordModel().'Peer';
        $i->add($model::ID, $this->getRecordId());
        $i->addDescendingOrderByColumn($model::CREATED_AT);
        return $i = $model::doSelect($i);

    }

    public function getType() {
        $return = '';
        switch ($this->getRecordModel()) {
            case 'text':
                $return = 'publication';
                break;
            case 'photo':
                $return = 'image';
                break;
            case 'album_photo':
                $return = 'album';
                break;
            case 'audio':
                $return = 'audio';
                break;
            case 'link':
                $return = 'website';
                break;
        }
        return $return;
    }

    public function getDescription() {
        $object = $this->getObject();
        $return = '';
        switch ($this->getRecordModel()) {
            case 'text':
                $return = $object[0]->getDescription();
                break;
            case 'photo':
                $return = $object[0]->getUser()->getName() . ' ha compartido una imagen a través de Social Sandbox.';
                break;
            case 'album_photo':
                $return = $object[0]->getUser()->getName() . ' ha compartido su album de fotos ' . $object[0]->getName() . ' a través de Social Sandbox.';
                break;
            case 'audio':
                $return = $object[0]->getUser()->getName() . ' ha compartido ' . $object[0]->getDescription() . ' a través de Social Sandbox.';
                ;
                break;
            case 'link':
                $return = $object[0]->getDescription();
                break;
        }
        return $return;
    }

    public function getImage() {
        $object = $this->getObject();
        $return = '';
        switch ($this->getRecordModel()) {
            case 'text':
                $return = sfConfig::get('app_base_url') . 'PubsPlugin/images/default_avatar.png';
                break;
            case 'photo':
                $return = $object[0]->getThumb();
                break;
            case 'album_photo':
                $return = $object[0]->getCover();
                break;
            case 'audio':
                $return = sfConfig::get('app_base_url') . 'PubsPlugin/images/default_avatar.png';
                break;
            case 'link':
                $return = $object[0]->getImage();
                break;
        }
        return $return;
    }

    public function getTitle() {
        $object = $this->getObject();
        $return = '';
        switch ($this->getRecordModel()) {
            case 'text':
                $return = 'Publication by ' . $object[0]->getUser()->getName();
                break;
            case 'photo':
                $return = $object[0]->getTitle();
                break;
            case 'album_photo':
                $return = $object[0]->getName();
                break;
            case 'audio':
                $return = $object[0]->getDescription();
                break;
            case 'link':
                $return = $object[0]->getTitle() . ' - Shared by ' . $this->getUser()->getName() . ' in Social Sandbox';
                break;
        }
        return $return;
    }

}

// Pubs
