<?php

/**
 * Skeleton subclass for performing query and update operations on the 'Pubs' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Aug 10 15:12:00 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.PubsPlugin.lib.model
 */
class PubsPeer extends BasePubsPeer {

    public static function retrieveObject($model,$id) {
        $c = new Criteria();
        $c->add(self::RECORD_MODEL, $model);
        $c->add(self::RECORD_ID, $id);
        return self::doSelectOne($c);
    }
    public static function retrieveObjectUsers($model,$id,$user,$dest_user) {
        $c = new Criteria();
        $c->add(self::USER_ID, $user);
        $c->add(self::DEST_USER_ID, $dest_user);
        $c->add(self::RECORD_MODEL, $model);
        $c->add(self::RECORD_ID, $id);
        return self::doSelectOne($c);
    }
    
    public static function retrieveById($id) {
        $c = new Criteria();
        $c->add(self::ID, $id);
        return self::doSelectOne($c);
    }

    public static function activatePub($id=null) {

        $con = Propel::getConnection();
        // select from...
        $c1 = new Criteria();
        $c1->add(self::ID, $id);

        // update set
        $c2 = new Criteria();
        $c2->add(self::IS_ACTIVE, true);

        BasePeer::doUpdate($c1, $c2, $con);
    }

    public static function insertPub($model=null, $id=null, $user=null, $dest=null) {

        $pub = new Pubs();
        $pub->setUserId($user);
        $pub->setDestUserId($dest);
        $pub->setRecordModel($model);
        $pub->setRecordId($id);
        //guardo el objeto
        $pub->save();
        return $pub;
    }

    public static function getPubs($user) {
        if (!is_numeric($user)) {
            $i = new Criteria();
            $i->add(sfGuardUserPeer::USERNAME, $user);
            $datos = sfGuardUserPeer::doSelectOne($i);
        } else {
            $i = new Criteria();
            $i->add(sfGuardUserPeer::ID, $user);
            $datos = sfGuardUserPeer::doSelectOne($i);
        }

        $i = new Criteria();
        $i->add(PubsPeer::USER_ID, $datos->getId());
        return count(PubsPeer::doSelect($i));
    }

}

// PubsPeer
