<?php

/**
 * Skeleton subclass for performing query and update operations on the 'Setting_has_User' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Aug 10 15:39:52 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.PubsPlugin.lib.model
 */
class SettingHasUserPeer extends BaseSettingHasUserPeer {
    
    public static function retrieveById($id) {
        $c = new Criteria();
        $c->add(self::ID, $id);
        return self::doSelectOne($c);
    }
    
    public static function SettingUser($user_id=null, $setting_id=null) {
        
       $i = new Criteria();
        $i->add(SettingHasUserPeer::USER_ID, $user_id);
        $i->add(SettingHasUserPeer::SETTING_ID, $setting_id);
        return $i = SettingHasUserPeer::doSelectOne($i);
        
    }

}

// SettingHasUserPeer
