<?php

/**
 * Skeleton subclass for performing query and update operations on the 'Text' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Aug 10 15:31:23 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.PubsPlugin.lib.model
 */
class TextPeer extends BaseTextPeer {

    public static function retrieveById($id) {
        $c = new Criteria();
        $c->add(self::ID, $id);
        return self::doSelectOne($c);
    }

}

// TextPeer
