<?php


/**
 * Skeleton subclass for representing a row from the 'sfGuardForgotPassword' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Aug 13 13:01:59 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    plugins.sfGuardPlugin.lib.model
 */
class Sfguardforgotpassword extends BaseSfguardforgotpassword {

} // Sfguardforgotpassword
