<?php

/**
 * Base class that represents a row from the 'Audio' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Aug 13 13:02:00 2011
 *
 * @package    plugins.PubsPlugin.lib.model.om
 */
abstract class BaseAudio extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        AudioPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the filename field.
	 * @var        string
	 */
	protected $filename;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * The value for the plays field.
	 * @var        int
	 */
	protected $plays;

	/**
	 * The value for the record_model field.
	 * @var        string
	 */
	protected $record_model;

	/**
	 * The value for the record_id field.
	 * @var        int
	 */
	protected $record_id;

	/**
	 * The value for the user_id field.
	 * @var        int
	 */
	protected $user_id;

	/**
	 * The value for the dest_user_id field.
	 * @var        int
	 */
	protected $dest_user_id;

	/**
	 * The value for the is_active field.
	 * Note: this column has a database default value of: false
	 * @var        boolean
	 */
	protected $is_active;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUserRelatedByUserId;

	/**
	 * @var        sfGuardUser
	 */
	protected $asfGuardUserRelatedByDestUserId;

	/**
	 * @var        array AudioHasPlaylist[] Collection to store aggregation of AudioHasPlaylist objects.
	 */
	protected $collAudioHasPlaylists;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAudioHasPlaylists.
	 */
	private $lastAudioHasPlaylistCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'AudioPeer';

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
		$this->is_active = false;
	}

	/**
	 * Initializes internal state of BaseAudio object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [filename] column value.
	 * 
	 * @return     string
	 */
	public function getFilename()
	{
		return $this->filename;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Get the [plays] column value.
	 * 
	 * @return     int
	 */
	public function getPlays()
	{
		return $this->plays;
	}

	/**
	 * Get the [record_model] column value.
	 * 
	 * @return     string
	 */
	public function getRecordModel()
	{
		return $this->record_model;
	}

	/**
	 * Get the [record_id] column value.
	 * 
	 * @return     int
	 */
	public function getRecordId()
	{
		return $this->record_id;
	}

	/**
	 * Get the [user_id] column value.
	 * 
	 * @return     int
	 */
	public function getUserId()
	{
		return $this->user_id;
	}

	/**
	 * Get the [dest_user_id] column value.
	 * 
	 * @return     int
	 */
	public function getDestUserId()
	{
		return $this->dest_user_id;
	}

	/**
	 * Get the [is_active] column value.
	 * 
	 * @return     boolean
	 */
	public function getIsActive()
	{
		return $this->is_active;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Audio The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = AudioPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [filename] column.
	 * 
	 * @param      string $v new value
	 * @return     Audio The current object (for fluent API support)
	 */
	public function setFilename($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->filename !== $v) {
			$this->filename = $v;
			$this->modifiedColumns[] = AudioPeer::FILENAME;
		}

		return $this;
	} // setFilename()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     Audio The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = AudioPeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Set the value of [plays] column.
	 * 
	 * @param      int $v new value
	 * @return     Audio The current object (for fluent API support)
	 */
	public function setPlays($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->plays !== $v) {
			$this->plays = $v;
			$this->modifiedColumns[] = AudioPeer::PLAYS;
		}

		return $this;
	} // setPlays()

	/**
	 * Set the value of [record_model] column.
	 * 
	 * @param      string $v new value
	 * @return     Audio The current object (for fluent API support)
	 */
	public function setRecordModel($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->record_model !== $v) {
			$this->record_model = $v;
			$this->modifiedColumns[] = AudioPeer::RECORD_MODEL;
		}

		return $this;
	} // setRecordModel()

	/**
	 * Set the value of [record_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Audio The current object (for fluent API support)
	 */
	public function setRecordId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->record_id !== $v) {
			$this->record_id = $v;
			$this->modifiedColumns[] = AudioPeer::RECORD_ID;
		}

		return $this;
	} // setRecordId()

	/**
	 * Set the value of [user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Audio The current object (for fluent API support)
	 */
	public function setUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->user_id !== $v) {
			$this->user_id = $v;
			$this->modifiedColumns[] = AudioPeer::USER_ID;
		}

		if ($this->asfGuardUserRelatedByUserId !== null && $this->asfGuardUserRelatedByUserId->getId() !== $v) {
			$this->asfGuardUserRelatedByUserId = null;
		}

		return $this;
	} // setUserId()

	/**
	 * Set the value of [dest_user_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Audio The current object (for fluent API support)
	 */
	public function setDestUserId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->dest_user_id !== $v) {
			$this->dest_user_id = $v;
			$this->modifiedColumns[] = AudioPeer::DEST_USER_ID;
		}

		if ($this->asfGuardUserRelatedByDestUserId !== null && $this->asfGuardUserRelatedByDestUserId->getId() !== $v) {
			$this->asfGuardUserRelatedByDestUserId = null;
		}

		return $this;
	} // setDestUserId()

	/**
	 * Set the value of [is_active] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Audio The current object (for fluent API support)
	 */
	public function setIsActive($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->is_active !== $v || $this->isNew()) {
			$this->is_active = $v;
			$this->modifiedColumns[] = AudioPeer::IS_ACTIVE;
		}

		return $this;
	} // setIsActive()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Audio The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = AudioPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			if ($this->is_active !== false) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->filename = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->description = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->plays = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->record_model = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->record_id = ($row[$startcol + 5] !== null) ? (int) $row[$startcol + 5] : null;
			$this->user_id = ($row[$startcol + 6] !== null) ? (int) $row[$startcol + 6] : null;
			$this->dest_user_id = ($row[$startcol + 7] !== null) ? (int) $row[$startcol + 7] : null;
			$this->is_active = ($row[$startcol + 8] !== null) ? (boolean) $row[$startcol + 8] : null;
			$this->created_at = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = AudioPeer::NUM_COLUMNS - AudioPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Audio object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->asfGuardUserRelatedByUserId !== null && $this->user_id !== $this->asfGuardUserRelatedByUserId->getId()) {
			$this->asfGuardUserRelatedByUserId = null;
		}
		if ($this->asfGuardUserRelatedByDestUserId !== null && $this->dest_user_id !== $this->asfGuardUserRelatedByDestUserId->getId()) {
			$this->asfGuardUserRelatedByDestUserId = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AudioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = AudioPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->asfGuardUserRelatedByUserId = null;
			$this->asfGuardUserRelatedByDestUserId = null;
			$this->collAudioHasPlaylists = null;
			$this->lastAudioHasPlaylistCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AudioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAudio:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				AudioPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAudio:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(AudioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseAudio:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			// symfony_timestampable behavior
			
			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
				// symfony_timestampable behavior
				if (!$this->isColumnModified(AudioPeer::CREATED_AT))
				{
				  $this->setCreatedAt(time());
				}

			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseAudio:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				AudioPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfGuardUserRelatedByUserId !== null) {
				if ($this->asfGuardUserRelatedByUserId->isModified() || $this->asfGuardUserRelatedByUserId->isNew()) {
					$affectedRows += $this->asfGuardUserRelatedByUserId->save($con);
				}
				$this->setsfGuardUserRelatedByUserId($this->asfGuardUserRelatedByUserId);
			}

			if ($this->asfGuardUserRelatedByDestUserId !== null) {
				if ($this->asfGuardUserRelatedByDestUserId->isModified() || $this->asfGuardUserRelatedByDestUserId->isNew()) {
					$affectedRows += $this->asfGuardUserRelatedByDestUserId->save($con);
				}
				$this->setsfGuardUserRelatedByDestUserId($this->asfGuardUserRelatedByDestUserId);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = AudioPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = AudioPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += AudioPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAudioHasPlaylists !== null) {
				foreach ($this->collAudioHasPlaylists as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->asfGuardUserRelatedByUserId !== null) {
				if (!$this->asfGuardUserRelatedByUserId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUserRelatedByUserId->getValidationFailures());
				}
			}

			if ($this->asfGuardUserRelatedByDestUserId !== null) {
				if (!$this->asfGuardUserRelatedByDestUserId->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->asfGuardUserRelatedByDestUserId->getValidationFailures());
				}
			}


			if (($retval = AudioPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAudioHasPlaylists !== null) {
					foreach ($this->collAudioHasPlaylists as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AudioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getFilename();
				break;
			case 2:
				return $this->getDescription();
				break;
			case 3:
				return $this->getPlays();
				break;
			case 4:
				return $this->getRecordModel();
				break;
			case 5:
				return $this->getRecordId();
				break;
			case 6:
				return $this->getUserId();
				break;
			case 7:
				return $this->getDestUserId();
				break;
			case 8:
				return $this->getIsActive();
				break;
			case 9:
				return $this->getCreatedAt();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = AudioPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getFilename(),
			$keys[2] => $this->getDescription(),
			$keys[3] => $this->getPlays(),
			$keys[4] => $this->getRecordModel(),
			$keys[5] => $this->getRecordId(),
			$keys[6] => $this->getUserId(),
			$keys[7] => $this->getDestUserId(),
			$keys[8] => $this->getIsActive(),
			$keys[9] => $this->getCreatedAt(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = AudioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setFilename($value);
				break;
			case 2:
				$this->setDescription($value);
				break;
			case 3:
				$this->setPlays($value);
				break;
			case 4:
				$this->setRecordModel($value);
				break;
			case 5:
				$this->setRecordId($value);
				break;
			case 6:
				$this->setUserId($value);
				break;
			case 7:
				$this->setDestUserId($value);
				break;
			case 8:
				$this->setIsActive($value);
				break;
			case 9:
				$this->setCreatedAt($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = AudioPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setFilename($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setDescription($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setPlays($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setRecordModel($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setRecordId($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setUserId($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setDestUserId($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setIsActive($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCreatedAt($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(AudioPeer::DATABASE_NAME);

		if ($this->isColumnModified(AudioPeer::ID)) $criteria->add(AudioPeer::ID, $this->id);
		if ($this->isColumnModified(AudioPeer::FILENAME)) $criteria->add(AudioPeer::FILENAME, $this->filename);
		if ($this->isColumnModified(AudioPeer::DESCRIPTION)) $criteria->add(AudioPeer::DESCRIPTION, $this->description);
		if ($this->isColumnModified(AudioPeer::PLAYS)) $criteria->add(AudioPeer::PLAYS, $this->plays);
		if ($this->isColumnModified(AudioPeer::RECORD_MODEL)) $criteria->add(AudioPeer::RECORD_MODEL, $this->record_model);
		if ($this->isColumnModified(AudioPeer::RECORD_ID)) $criteria->add(AudioPeer::RECORD_ID, $this->record_id);
		if ($this->isColumnModified(AudioPeer::USER_ID)) $criteria->add(AudioPeer::USER_ID, $this->user_id);
		if ($this->isColumnModified(AudioPeer::DEST_USER_ID)) $criteria->add(AudioPeer::DEST_USER_ID, $this->dest_user_id);
		if ($this->isColumnModified(AudioPeer::IS_ACTIVE)) $criteria->add(AudioPeer::IS_ACTIVE, $this->is_active);
		if ($this->isColumnModified(AudioPeer::CREATED_AT)) $criteria->add(AudioPeer::CREATED_AT, $this->created_at);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(AudioPeer::DATABASE_NAME);

		$criteria->add(AudioPeer::ID, $this->id);
		$criteria->add(AudioPeer::USER_ID, $this->user_id);
		$criteria->add(AudioPeer::DEST_USER_ID, $this->dest_user_id);

		return $criteria;
	}

	/**
	 * Returns the composite primary key for this object.
	 * The array elements will be in same order as specified in XML.
	 * @return     array
	 */
	public function getPrimaryKey()
	{
		$pks = array();

		$pks[0] = $this->getId();

		$pks[1] = $this->getUserId();

		$pks[2] = $this->getDestUserId();

		return $pks;
	}

	/**
	 * Set the [composite] primary key.
	 *
	 * @param      array $keys The elements of the composite key (order must match the order in XML file).
	 * @return     void
	 */
	public function setPrimaryKey($keys)
	{

		$this->setId($keys[0]);

		$this->setUserId($keys[1]);

		$this->setDestUserId($keys[2]);

	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Audio (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setFilename($this->filename);

		$copyObj->setDescription($this->description);

		$copyObj->setPlays($this->plays);

		$copyObj->setRecordModel($this->record_model);

		$copyObj->setRecordId($this->record_id);

		$copyObj->setUserId($this->user_id);

		$copyObj->setDestUserId($this->dest_user_id);

		$copyObj->setIsActive($this->is_active);

		$copyObj->setCreatedAt($this->created_at);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAudioHasPlaylists() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAudioHasPlaylist($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Audio Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     AudioPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new AudioPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     Audio The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUserRelatedByUserId(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setUserId(NULL);
		} else {
			$this->setUserId($v->getId());
		}

		$this->asfGuardUserRelatedByUserId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addAudioRelatedByUserId($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUserRelatedByUserId(PropelPDO $con = null)
	{
		if ($this->asfGuardUserRelatedByUserId === null && ($this->user_id !== null)) {
			$this->asfGuardUserRelatedByUserId = sfGuardUserPeer::retrieveByPk($this->user_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUserRelatedByUserId->addAudiosRelatedByUserId($this);
			 */
		}
		return $this->asfGuardUserRelatedByUserId;
	}

	/**
	 * Declares an association between this object and a sfGuardUser object.
	 *
	 * @param      sfGuardUser $v
	 * @return     Audio The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setsfGuardUserRelatedByDestUserId(sfGuardUser $v = null)
	{
		if ($v === null) {
			$this->setDestUserId(NULL);
		} else {
			$this->setDestUserId($v->getId());
		}

		$this->asfGuardUserRelatedByDestUserId = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the sfGuardUser object, it will not be re-added.
		if ($v !== null) {
			$v->addAudioRelatedByDestUserId($this);
		}

		return $this;
	}


	/**
	 * Get the associated sfGuardUser object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     sfGuardUser The associated sfGuardUser object.
	 * @throws     PropelException
	 */
	public function getsfGuardUserRelatedByDestUserId(PropelPDO $con = null)
	{
		if ($this->asfGuardUserRelatedByDestUserId === null && ($this->dest_user_id !== null)) {
			$this->asfGuardUserRelatedByDestUserId = sfGuardUserPeer::retrieveByPk($this->dest_user_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->asfGuardUserRelatedByDestUserId->addAudiosRelatedByDestUserId($this);
			 */
		}
		return $this->asfGuardUserRelatedByDestUserId;
	}

	/**
	 * Clears out the collAudioHasPlaylists collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAudioHasPlaylists()
	 */
	public function clearAudioHasPlaylists()
	{
		$this->collAudioHasPlaylists = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAudioHasPlaylists collection (array).
	 *
	 * By default this just sets the collAudioHasPlaylists collection to an empty array (like clearcollAudioHasPlaylists());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAudioHasPlaylists()
	{
		$this->collAudioHasPlaylists = array();
	}

	/**
	 * Gets an array of AudioHasPlaylist objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Audio has previously been saved, it will retrieve
	 * related AudioHasPlaylists from storage. If this Audio is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array AudioHasPlaylist[]
	 * @throws     PropelException
	 */
	public function getAudioHasPlaylists($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AudioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAudioHasPlaylists === null) {
			if ($this->isNew()) {
			   $this->collAudioHasPlaylists = array();
			} else {

				$criteria->add(AudioHasPlaylistPeer::AUDIO_ID, $this->id);

				AudioHasPlaylistPeer::addSelectColumns($criteria);
				$this->collAudioHasPlaylists = AudioHasPlaylistPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AudioHasPlaylistPeer::AUDIO_ID, $this->id);

				AudioHasPlaylistPeer::addSelectColumns($criteria);
				if (!isset($this->lastAudioHasPlaylistCriteria) || !$this->lastAudioHasPlaylistCriteria->equals($criteria)) {
					$this->collAudioHasPlaylists = AudioHasPlaylistPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAudioHasPlaylistCriteria = $criteria;
		return $this->collAudioHasPlaylists;
	}

	/**
	 * Returns the number of related AudioHasPlaylist objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related AudioHasPlaylist objects.
	 * @throws     PropelException
	 */
	public function countAudioHasPlaylists(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AudioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAudioHasPlaylists === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AudioHasPlaylistPeer::AUDIO_ID, $this->id);

				$count = AudioHasPlaylistPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AudioHasPlaylistPeer::AUDIO_ID, $this->id);

				if (!isset($this->lastAudioHasPlaylistCriteria) || !$this->lastAudioHasPlaylistCriteria->equals($criteria)) {
					$count = AudioHasPlaylistPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAudioHasPlaylists);
				}
			} else {
				$count = count($this->collAudioHasPlaylists);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a AudioHasPlaylist object to this object
	 * through the AudioHasPlaylist foreign key attribute.
	 *
	 * @param      AudioHasPlaylist $l AudioHasPlaylist
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAudioHasPlaylist(AudioHasPlaylist $l)
	{
		if ($this->collAudioHasPlaylists === null) {
			$this->initAudioHasPlaylists();
		}
		if (!in_array($l, $this->collAudioHasPlaylists, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAudioHasPlaylists, $l);
			$l->setAudio($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Audio is new, it will return
	 * an empty collection; or if this Audio has previously
	 * been saved, it will retrieve related AudioHasPlaylists from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Audio.
	 */
	public function getAudioHasPlaylistsJoinPlaylist($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(AudioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAudioHasPlaylists === null) {
			if ($this->isNew()) {
				$this->collAudioHasPlaylists = array();
			} else {

				$criteria->add(AudioHasPlaylistPeer::AUDIO_ID, $this->id);

				$this->collAudioHasPlaylists = AudioHasPlaylistPeer::doSelectJoinPlaylist($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(AudioHasPlaylistPeer::AUDIO_ID, $this->id);

			if (!isset($this->lastAudioHasPlaylistCriteria) || !$this->lastAudioHasPlaylistCriteria->equals($criteria)) {
				$this->collAudioHasPlaylists = AudioHasPlaylistPeer::doSelectJoinPlaylist($criteria, $con, $join_behavior);
			}
		}
		$this->lastAudioHasPlaylistCriteria = $criteria;

		return $this->collAudioHasPlaylists;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAudioHasPlaylists) {
				foreach ((array) $this->collAudioHasPlaylists as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAudioHasPlaylists = null;
			$this->asfGuardUserRelatedByUserId = null;
			$this->asfGuardUserRelatedByDestUserId = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseAudio:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseAudio::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseAudio
