<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/17 16:30:28
sfConfig::add(array(
  'mod_sfguardregister_enabled' => true,
  'mod_sfguardregister_view_class' => 'sfPHP',
  'mod_sfguardregister_is_internal' => false,
));
