<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/17 16:30:32
sfConfig::add(array(
  'mod_follow_enabled' => true,
  'mod_follow_view_class' => 'sfPHP',
  'mod_follow_is_internal' => false,
));
