<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2011/08/17 16:30:28
sfConfig::add(array(
  'mod_pubs_enabled' => true,
  'mod_pubs_view_class' => 'sfPHP',
  'mod_pubs_is_internal' => false,
));
